language: android
jdk: oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle/caches/3.3
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper
before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools
    - extra-google-google_play_services
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-25

licenses:
    - 'android-sdk-license-c81a61d9'
    - 'android-sdk-license-.+'


script:
  - ./build.sh
